name = "coding-brain-backend"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "coding-brain-db"
database_id = "774a7e48-fc91-48b0-b507-8478a2989988"


[[r2_buckets]]
binding = "ASSETS_BUCKET"
bucket_name = "coding-brain-assets"

[[queues.producers]]
queue = "execution-queue"
binding = "EXECUTION_QUEUE"


[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "EXECUTION_COORDINATOR"
class_name = "ExecutionCoordinator"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ExecutionCoordinator"]
